### ISSUE TITLE
Cannot specify GitCloneTask

### ISSUE THREAD

**Issue by ngiger** [a-langer/eclipse-oomph-console#4]
I tried to convert our [oomph Elexis.setup]( https://github.com/elexis/elexis-3-core/blob/master/ch.elexis.sdk/Elexis.setup) to eclipse-oomph-console.
Some very important things work. Thanks for your work!

However I was unable make gitClone work.  I tried to specify all used variable in my bash script setup_elexis.sh for the git.clone operation, but was unsuccessful to make it work

My current state can be found under https://github.com/ngiger/elexis-ide.

Also I was puzzled (and lost some time) because it seems to me that the

>  repository
>             url="https://download.eclipse.org/releases/${eclipse.train}">

must be the last one. If not it, the repositories mentioned later, were silently ignored. Is this correct? If so, it just be mentioned in the readme (or set example)

**Comment by a-langer** [comment]
Hello, the console plugin does not affect the execution logic of the Oomph installer. When creating an setup model, we can be guided by the official [documentation](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/html/concepts/DocTask.html):

> There are three types of [triggers](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/javadoc/org/eclipse/oomph/setup/Trigger.html): 
> -  [Bootstrap](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/javadoc/org/eclipse/oomph/setup/Trigger.html#BOOTSTRAP) applies when using the [installer wizard](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/html/user/wizard/DocInstallWizard.html).
> -  [Startup](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/javadoc/org/eclipse/oomph/setup/Trigger.html#STARTUP) applies when a product is first launched, automated task performance is enabled, and there are tasks that need to be performed, at which point the [execution wizard](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/html/user/wizard/DocUpdateWizard.html) will be opened on the [progressPage page](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/html/user/wizard/DocConfirmationPage.html).
> - [Manual](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/javadoc/org/eclipse/oomph/setup/Trigger.html#MANUAL) applies when invoking the [project wizard](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/html/user/wizard/DocImportWizard.html) or directly invoking [execution wizard](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/html/user/wizard/DocUpdateWizard.html).
> 
> Each task specifies its [valid](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/html/concepts/DocTask.html.excludedTriggers) triggers determining whether that task is [filtered](https://help.eclipse.org/latest/topic/org.eclipse.oomph.setup.doc/html/concepts/DocTaskComposition.html#Filter) when tasks are gathered.

According to the answers on the Eclipse forum, tasks with type "GitCloneTask" can only be executed when the IDE is started (i.e. STARTUP or MANUAL):
- [Order of git checkout and resource copy](https://www.eclipse.org/forums/index.php?t=msg&th=1068738&goto=1702576&#msg_1702576):
  > For obvious reasons the GitCloneTask can only perform on the STARTUP and MANUAL triggers.
- [Git Clone Tasks not triggert when using own index](https://www.eclipse.org/forums/index.php?t=msg&th=1070150&goto=1707842&#msg_1707842):
  > Just to be clear, the gitclonetask cannot run in the installer (i.e., on boostrap trigger). 

Based on this, I conclude that tasks with type "GitCloneTask" cannot be executed from the installer, because this is the design. You can try running STARTUP triggers from the IDE by running the Eclipse workspace initialization command after the installer is complete:
```bash
# Linux
./eclipse -initialize -data ./workspace
# Windows
.\eclipsec.exe -initialize -data .\workspace
```
Hope this helps.

**Comment by ngiger** [comment]
Thanks for your detailed answer, which was very helpful for me! I will try to make the STARTUP trigger work.
